EEE/urls.py

from django.urls import path
from EEE import views


app_name = "EEE"


from EEE.views import StudentReg


urlpatterns = [
    path('home', views.home, name = "home"),
    path('products', views.products, name = "products"),
    path('service', views.service, name = "service"),
    path('aboutus', views.aboutus, name = "aboutus"),
    path('contactus', views.contactus, name = "contactus"),

    path('studentreg', StudentReg.as_view(), name = 'studentreg'),

# for class based views
     path('student',views.student, name = 'student'),
    path('form', views.form,name  = 'form'),
    path('detail/<int:id>', views.detail, name = 'detail'),
    path('update/<int:id>', views.update, name = 'update'),
    path('delete/<int:id>', views.delete, name = 'delete'),
    path('update/form', views.update, name = 'update'),

    path('',views.rit, name = ''),
    path('get1', views.get1, name = 'get1'),
    path('post1', views.post1, name = 'post1'),


# for templates eee

    path('about', views.about, name = 'about'),
    path('blog_single', views.blog_single, name = 'blog_single'),
    path('blog', views.blog, name = 'blog'),
    path('contact', views.contact, name = 'contact'),
    path('index', views.index, name = 'index'),
    path('portfolio', views.portfolio, name = 'portfolio'),  

   #for user login and log out
   path('register', views.register, name = 'register'),
    path('login_reg', views.login_reg, name = 'login'),
    path('logout', views.logoutuser, name = 'logout'),
 
]

EEE/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=20)
    department = models.CharField(max_length=20)
    age = models.IntegerField()
    gender = models.CharField(max_length=1)
    def __str__(self):
        return self.name

EEE/forms.py
from django.forms import ModelForm

from .models import Student

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

# for user registeration sing and sign out
from django import forms
from django.forms import ModelForm 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

EEE/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required 



# Create your views here.

def home(request):
    stu = "kayal"
    names = ['karthick', 'raju', 'praveen']
    context = {'stu': stu, 'names': names}

    return render(request, 'home.html', context)

def products(request):
    return render(request, 'products.html')

def service(request):
    return render(request, 'service.html')

def aboutus(request):
    return render(request, 'aboutus.html')

def contactus(request):
    return render(request, 'contactus.html')

def about(request):
    return render(request, 'EEE/about.html')

def blog_single(request):
    return render(request, 'EEE/blog-single.html')

def blog(request):
    return render(request, 'EEE/blog.html')

@login_required(login_url = 'EEE:login')
def contact(request):
    return render(request, 'EEE/contact.html')

def index(request):
    return render(request, 'EEE/index.html')

def portfolio(request):
    return render(request, 'EEE/portfolio.html')

from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView

from EEE.models import Student
 
class StudentReg(CreateView):
	model = Student
	fields = '__all__'
	template_name = 'CBV/studentreg.html'
	success_url ="/"

from django.shortcuts import render, redirect, get_object_or_404

from .models import Student
from .forms import StudentForm

def student(request):
    stu = Student.objects.all()
    context = {'stu': stu}
    return render(request, 'student.html', context)


def detail(request, id):
	data = Student.objects.get(id = id)	
	context = {'data':data}
	return render(request,'detail.html', context)


def update(request, id):
	obj = get_object_or_404(Student, id =id)
	form = StudentForm(request.POST or None, instance = obj)
	data = Student.objects.get(id = id)
	if form.is_valid():
		form.save()
		return redirect('EEE:form')

	context = {'form':form, 'data':data}
	return render(request,'update.html', context )


def delete(request, id):
	data = Student.objects.get(id = id)
	context = {'data':data}
	if request.method =='POST':
		data.delete()
		return redirect('EEE:form')
	return render(request,'delete.html', context )


def form(request):
    stu = Student.objects.all() 

    form = StudentForm
    if request.method =="POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('EEE:student')  

    context = {'stu': stu, 'form': form}
    return render(request, 'form.html', context)

def rit(request):
	return render(request,'rit.html')

def get1(request):
	a = int(request.GET['num1'])
	b = int(request.GET['num2'])
	c = a*b
	context = {'c': c }
	return render(request,'get.html',context)

def post1(request):
	a = int(request.POST['num1'])
	b = int(request.POST['num2'])
	c = a*b
	context = {'c': c }
	return render(request,'post.html',context)
from django.shortcuts import render, redirect
from .forms import CreateUserForm 

from django.contrib.auth import login
from django.contrib import messages

# # from django.contrib.auth.forms import UserCreationForm
# from django.contrib import messages 
# #from django.contrib import authenticate, login, logout
# from django.contrib.auth import authenticate, login, logout

# from django.contrib.auth.decorators import login_required 


# def register(request):
	
# 	form = CreateUserForm()

# 	if request.method == 'POST':
# 		form = CreateUserForm(request.POST)
# 		if form.is_valid():
# 			form.save()
# 			user = form.cleaned_data.get('username')
# 			messages.success(request, 'Your Account has been created for '+ user)
# 			return redirect('EEE:login')


# 	context = { 'form': form }
# 	return render (request, 'register.html', context)


# def login_reg(request):

# 	if request.method =='POST':
# 		username = request.POST.get('username')
# 		password = request.POST.get('password')
# 		user = authenticate(request, username = username, password = password)
# 		if user is not None:
# 			login(request, user)
# 			return redirect('EEE:home')
# 		else:
# 			messages.info(request, "Username Or password is incorrect.")
# 	context = {}
# 	return render (request, 'login.html', context)

# def logoutuser(request):
# 	logout(request)
# 	return redirect('EEE:login')





# re-workfrom django.shortcuts import render, redirect
from .forms import CreateUserForm 

from django.contrib.auth import login
from django.contrib import messages

# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages 
#from django.contrib import authenticate, login, logout
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required 







def register(request):
	
	form = CreateUserForm()

	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			user = form.cleaned_data.get('username')
			messages.success(request, 'Your Account has been created for '+ user)
			return redirect('EEE:login')


	context = { 'form': form }
	return render (request, 'register.html', context)


def login_reg(request):

	if request.method =='POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(request, username = username, password = password)
		if user is not None:
			login(request, user)
			return redirect('EEE:index')
		else:
			messages.info(request, "Username Or password is incorrect.")


	context = {}
	return render (request, 'login.html', context)

def logoutuser(request):
	logout(request)
	return redirect('EEE:login')

EEE/templates/EEE/about.html
{% load static %}

<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Kross - Creative Portfolio Template</title>

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Creative Portfolio Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Themefisher Kross Template v1.0">
  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}" />
  
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
    <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body>
  

<header class="navigation fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand font-tertiary h3" href="index.html"><img src="{% static 'images/logo.png' %}" alt="Myself"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
      aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'EEE:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'EEE:about' %}">about</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'EEE:blog' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'EEE:portfolio' %}">Portfolio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'EEE:contact' %}">Contact</a>
        </li>
      </ul>
    </div>
  </nav>
</header>

<!-- page title -->
<section class="page-title-alt bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h2 class="text-white font-tertiary">Hello ...AP..BYE..BYE..YCP.</h2>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{% static 'images/illustrations/leaf-bg-top.png' %}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{% static 'images/illustrations/dots-group-sm.png' %}" alt="illustrations" class="bg-shape-2">
  <img src="{% static 'images/illustrations/leaf-yellow.png' %}" alt="illustrations" class="bg-shape-3">
  <img src="{% static 'images/illustrations/leaf-orange.png' %}" alt="illustrations" class="bg-shape-4">
  <img src="{% static 'images/illustrations/dots-group-cyan.png' %}" alt="illustrations" class="bg-shape-5">
  <img src="{% static 'images/illustrations/leaf-cyan-lg.png' %}" alt="illustrations" class="bg-shape-6">
</section>
<!-- /page title -->

<!-- about -->
<section class="section pt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <p>myself gupta i am currently pursuing my btech in srkr engineering college
          i am big fan and follower of power star pavan kalyan.</p>
        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
          Excepteur sint occaecat cupidatat non proident.</p>
        <p>Deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem
          accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi
          architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia.</p>
      </div>
      <div class="col-md-4 text-center drag-lg-top">
        <div class="shadow-down mb-4">
          <img src="{% static 'images/about/gupta.jpeg' %}" alt="author" class="img-fluid w-100 rounded-lg border-thick border-white">
        </div>
        <img src="{% static 'images/about/pspk.jpeg' %}" alt="signature" class="img-fluid">
        <h4>BABULAKE BABU KALYAN BABU</h4>
      </div>
    </div>
  </div>
</section>
<!-- /about -->
g
<!-- Work Process -->
<section class="section">
  <div class="container">
    <div class="row justify-content-around">
      <div class="col-lg-12 text-center">
        <h2 class="section-title">Work Process</h2>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <div class="">
          <img src="{% static 'images/icons/plan.png' %}" class="mb-4" alt="icon">
          <h4 class="mb-4">Research and Plan</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <img src="{% static 'images/icons/design.png' %}" class="mb-4" alt="icon">
        <h4 class="mb-4">Design and Develop</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
          dolore magna aliqua.</p>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <img src="{% static 'images/icons/print.png' %}" class="mb-4" alt="icon">
        <h4 class="mb-4">Deliver</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
          dolore magna aliqua.</p>
      </div>
    </div>
  </div>
</section>
<!-- ./Work Process -->

<!-- team -->
<section class="section bg-cover" data-background="images/backgrounds/team-bg.png">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">My Team</h2>
      </div>
      <div class="col-md-4 col-sm-6 mb-4 mb-md-0">
        <div class="card text-center">
          <img src="{% static 'images/team/member-1.png' %}" class="card-img-top">
          <div class="card-body">
            <h4 class="card-title">Jack Schenziwe</h4>
            <p class="text-light font-secondary">Project Manager</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 mb-4 mb-md-0">
        <div class="card text-center">
          <img src="{% static 'images/team/member-2.png' %}" class="card-img-top">
          <div class="card-body">
            <h4 class="card-title">Jack Schenziwe</h4>
            <p class="text-light font-secondary">Project Manager</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 mb-4 mb-md-0">
        <div class="card text-center">
          <img src="{% static 'images/team/member-3.png' %}" class="card-img-top">
          <div class="card-body">
            <h4 class="card-title">Jack Schenziwe</h4>
            <p class="text-light font-secondary">Project Manager</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /team -->

<!-- clients -->
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">My Clients</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="client-logo-slider d-flex align-items-center">
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-1.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-2.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-3.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-4.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-5.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-1.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-2.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-3.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-4.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-5.png' %}" alt="client-logo"></a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /clients -->

<!-- contact -->
<section class="section section-on-footer" data-background="images/backgrounds/bg-dots.png">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">Contact Info</h2>
      </div>
      <div class="col-lg-8 mx-auto">
        <div class="bg-white rounded text-center p-5 shadow-down">
          <h4 class="mb-80">Contact Form</h4>
          <form action="#" class="row">
            <div class="col-md-6">
              <input type="text" id="name" name="name" placeholder="Full Name" class="form-control px-0 mb-4" required>
            </div>
            <div class="col-md-6">
              <input type="email" id="email" name="email" placeholder="Email Address" class="form-control px-0 mb-4" required>
            </div>
            <div class="col-12">
              <textarea name="message" id="message" class="form-control px-0 mb-4"
                placeholder="Type Message Here" required></textarea>
            </div>
            <div class="col-lg-6 col-10 mx-auto">
              <button class="btn btn-primary w-100">send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /contact -->

<!-- footer -->
<footer class="bg-dark footer-section">
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h5 class="text-light">Email</h5>
          <p class="text-white paragraph-lg font-secondary">steve.fruits@email.com</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Phone</h5>
          <p class="text-white paragraph-lg font-secondary">+880 2544 658 256</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Address</h5>
          <p class="text-white paragraph-lg font-secondary">125/A, CA Commercial Area, California, USA</p>
        </div>
      </div>
    </div>
  </div>
  <div class="border-top text-center border-dark py-5">
    <p class="mb-0 text-light">Copyright &copy;<script>
        var CurrentYear = new Date().getFullYear()
        document.write(CurrentYear)
      </script> Designed &amp; Developed by <a class="text-white-50" href="Themefisher">Themefisher</a></p>
  </div>
</footer>
<!-- /footer -->

<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- filter -->
<script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

EEE/templates/EEE/contact.html
{% load static %}

<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Kross - Creative Portfolio Template</title>

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Creative Portfolio Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Themefisher Kross Template v1.0">
  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}" />
  
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body>
  

<header class="navigation fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand font-tertiary h3" href="index.html"><img src="{% static 'images/logo.png' %} " alt="Myself"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
      aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'EEE:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'EEE:about' %}">about</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'EEE:blog' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'EEE:portfolio' %}">Portfolio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'EEE:contact' %}">Contact</a>
        </li>
      </ul>
    </div>
  </nav>
</header>

<!-- page title -->
<section class="page-title bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="text-white font-tertiary">Contacts</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{% static 'images/illustrations/page-title.png' %}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{% static 'images/illustrations/leaf-pink-round.png' %}" alt="illustrations" class="bg-shape-2">
  <img src="{% static 'images/illustrations/dots-cyan.png' %}" alt="illustrations" class="bg-shape-3">
  <img src="{% static 'images/illustrations/leaf-orange.png' %}" alt="illustrations" class="bg-shape-4">
  <img src="{% static 'images/illustrations/leaf-yellow.png' %}" alt="illustrations" class="bg-shape-5">
  <img src="{% static 'images/illustrations/dots-group-cyan.png' %}" alt="illustrations" class="bg-shape-6">
  <img src="{% static 'images/illustrations/leaf-cyan-lg.png' %}" alt="illustrations" class="bg-shape-7">
</section>
<!-- /page title -->

<!-- contact -->
<section class="section section-on-footer" data-background="{% static 'images/backgrounds/bg-dots.png' %}">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">Contact Info</h2>
      </div>
      <div class="col-lg-8 mx-auto">
        <div class="bg-white rounded text-center p-5 shadow-down">
          <h4 class="mb-80">Contact Form</h4>
          <form action="#" class="row">
            <div class="col-md-6">
              <input type="text" id="name" name="name" placeholder="Full Name" class="form-control px-0 mb-4" required>
            </div>
            <div class="col-md-6">
              <input type="email" id="email" name="email" placeholder="Email Address" class="form-control px-0 mb-4" required>
            </div>
            <div class="col-12">
              <textarea name="message" id="message" class="form-control px-0 mb-4"
                placeholder="Type Message Here" required></textarea>
            </div>
            <div class="col-lg-6 col-10 mx-auto">
              <button class="btn btn-primary w-100">send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /contact -->

<!-- footer -->
<footer class="bg-dark footer-section">
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h5 class="text-light">Email</h5>
          <p class="text-white paragraph-lg font-secondary">steve.fruits@email.com</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Phone</h5>
          <p class="text-white paragraph-lg font-secondary">+880 2544 658 256</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Address</h5>
          <p class="text-white paragraph-lg font-secondary">125/A, CA Commercial Area, California, USA</p>
        </div>
      </div>
    </div>
  </div>
  <div class="border-top text-center border-dark py-5">
    <p class="mb-0 text-light">Copyright &copy;<script>
        var CurrentYear = new Date().getFullYear()
        document.write(CurrentYear)
      </script> Designed &amp; Developed by <a class="text-white-50" href="Themefisher">Themefisher</a></p>
  </div>
</footer>
<!-- /footer -->

<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- filter -->
<script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>