EEE/urls.py

from django.urls import path
from EEE import views


app_name = "EEE"


from EEE.views import StudentReg


urlpatterns = [
    path('home', views.home, name = "home"),
    path('products', views.products, name = "products"),
    path('service', views.service, name = "service"),
    path('aboutus', views.aboutus, name = "aboutus"),
    path('contactus', views.contactus, name = "contactus"),

    path('studentreg', StudentReg.as_view(), name = 'studentreg'),

# for class based views
     path('student',views.student, name = 'student'),
    path('form', views.form,name  = 'form'),
    path('detail/<int:id>', views.detail, name = 'detail'),
    path('update/<int:id>', views.update, name = 'update'),
    path('delete/<int:id>', views.delete, name = 'delete'),
    path('update/form', views.update, name = 'update'),

    path('',views.rit, name = ''),
    path('get1', views.get1, name = 'get1'),
    path('post1', views.post1, name = 'post1'),


# for templates eee

    path('about', views.about, name = 'about'),
    path('blog_single', views.blog_single, name = 'blog_single'),
    path('blog', views.blog, name = 'blog'),
    path('contact', views.contact, name = 'contact'),
    path('index', views.index, name = 'index'),
    path('portfolio', views.portfolio, name = 'portfolio'),  

   #for user login and log out
   path('register', views.register, name = 'register'),
    path('login_reg', views.login_reg, name = 'login'),
    path('logout', views.logoutuser, name = 'logout'),
 
]

SRKR/urls.py
from django.contrib import admin
from django.urls import path, include
from EEE import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('EEE', include("EEE.urls")),
    # for register, login, logout
    path('register', views.register, name = 'register'),
    path('login_reg', views.login_reg, name = 'login'),
    path('logout', views.logoutuser, name = 'logout'),
 
]

EEE/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=20)
    department = models.CharField(max_length=20)
    age = models.IntegerField()
    gender = models.CharField(max_length=1)
    def __str__(self):
        return self.name

EEE/forms.py
from django.forms import ModelForm

from .models import Student

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

# for user registeration sing and sign out
from django import forms
from django.forms import ModelForm 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

EEE/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required 



# Create your views here.

def home(request):
    stu = "kayal"
    names = ['karthick', 'raju', 'praveen']
    context = {'stu': stu, 'names': names}

    return render(request, 'home.html', context)

def products(request):
    return render(request, 'products.html')

def service(request):
    return render(request, 'service.html')

def aboutus(request):
    return render(request, 'aboutus.html')

def contactus(request):
    return render(request, 'contactus.html')

def about(request):
    return render(request, 'EEE/about.html')

def blog_single(request):
    return render(request, 'EEE/blog-single.html')

def blog(request):
    return render(request, 'EEE/blog.html')

@login_required(login_url = 'EEE:login')
def contact(request):
    return render(request, 'EEE/contact.html')

def index(request):
    return render(request, 'EEE/index.html')

def portfolio(request):
    return render(request, 'EEE/portfolio.html')

from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView

from EEE.models import Student
 
class StudentReg(CreateView):
	model = Student
	fields = '__all__'
	template_name = 'CBV/studentreg.html'
	success_url ="/"

from django.shortcuts import render, redirect, get_object_or_404

from .models import Student
from .forms import StudentForm

def student(request):
    stu = Student.objects.all()
    context = {'stu': stu}
    return render(request, 'student.html', context)


def detail(request, id):
	data = Student.objects.get(id = id)	
	context = {'data':data}
	return render(request,'detail.html', context)


def update(request, id):
	obj = get_object_or_404(Student, id =id)
	form = StudentForm(request.POST or None, instance = obj)
	data = Student.objects.get(id = id)
	if form.is_valid():
		form.save()
		return redirect('EEE:form')

	context = {'form':form, 'data':data}
	return render(request,'update.html', context )


def delete(request, id):
	data = Student.objects.get(id = id)
	context = {'data':data}
	if request.method =='POST':
		data.delete()
		return redirect('EEE:form')
	return render(request,'delete.html', context )


def form(request):
    stu = Student.objects.all() 

    form = StudentForm
    if request.method =="POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('EEE:student')  

    context = {'stu': stu, 'form': form}
    return render(request, 'form.html', context)

def rit(request):
	return render(request,'rit.html')

def get1(request):
	a = int(request.GET['num1'])
	b = int(request.GET['num2'])
	c = a*b
	context = {'c': c }
	return render(request,'get.html',context)

def post1(request):
	a = int(request.POST['num1'])
	b = int(request.POST['num2'])
	c = a*b
	context = {'c': c }
	return render(request,'post.html',context)
from django.shortcuts import render, redirect
from .forms import CreateUserForm 

from django.contrib.auth import login
from django.contrib import messages

# # from django.contrib.auth.forms import UserCreationForm
# from django.contrib import messages 
# #from django.contrib import authenticate, login, logout
# from django.contrib.auth import authenticate, login, logout

# from django.contrib.auth.decorators import login_required 


# def register(request):
	
# 	form = CreateUserForm()

# 	if request.method == 'POST':
# 		form = CreateUserForm(request.POST)
# 		if form.is_valid():
# 			form.save()
# 			user = form.cleaned_data.get('username')
# 			messages.success(request, 'Your Account has been created for '+ user)
# 			return redirect('EEE:login')


# 	context = { 'form': form }
# 	return render (request, 'register.html', context)


# def login_reg(request):

# 	if request.method =='POST':
# 		username = request.POST.get('username')
# 		password = request.POST.get('password')
# 		user = authenticate(request, username = username, password = password)
# 		if user is not None:
# 			login(request, user)
# 			return redirect('EEE:home')
# 		else:
# 			messages.info(request, "Username Or password is incorrect.")
# 	context = {}
# 	return render (request, 'login.html', context)

# def logoutuser(request):
# 	logout(request)
# 	return redirect('EEE:login')





# re-workfrom django.shortcuts import render, redirect
from .forms import CreateUserForm 

from django.contrib.auth import login
from django.contrib import messages

# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages 
#from django.contrib import authenticate, login, logout
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required 







def register(request):
	
	form = CreateUserForm()

	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			user = form.cleaned_data.get('username')
			messages.success(request, 'Your Account has been created for '+ user)
			return redirect('EEE:login')


	context = { 'form': form }
	return render (request, 'register.html', context)


def login_reg(request):

	if request.method =='POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(request, username = username, password = password)
		if user is not None:
			login(request, user)
			return redirect('EEE:index')
		else:
			messages.info(request, "Username Or password is incorrect.")


	context = {}
	return render (request, 'login.html', context)

def logoutuser(request):
	logout(request)
	return redirect('EEE:login')

templates/CBV/studentreg.html
<h1>Enroll or Register The student Details here.</h1>

<form method="POST" enctype="multipart/form-data">
 
    {% csrf_token %}
 
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

templates/aboutus.html
{% extends "base.html" %}

{% block content %}

This is my aboutus page.

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'EEE:home' %}">Home</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'EEE:products' %}">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'EEE:service' %}">Service</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'EEE:aboutus' %}">About us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'EEE:contactus' %}">Contact</a>
              </li>
              


            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    {% block content %}

    
    {% endblock %}</body>
</html>

templates/base12.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'IT:ome' %}">Home</a>
              </li>

              
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'IT:products' %}">products</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'IT:service' %}">service</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'IT:contactus' %}">Contactus</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'IT:aboutus' %}">aboutus</a>
              </li>




            </ul>
            
          </div>
        </div>
      </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    {% block content %}
    {% endblock %}
    {name}
</body>
</html>

templates/contactus.html
{% extends "base.html" %}

{% block content %}

This is my Contactus page.

{% endblock %}

templates/delete.html
{% extends "base.html" %}

{% block content %}


<div class="main">
    <!-- Create a Form -->
<form method="POST">
        <!-- Security token by Django -->
    {% csrf_token %}

<h4>    Are you want to delete this item ?</h4><br>

-
    <div>
        <table style="width:100%"; border-spacing: 5px;>

            <tr>
                <th>Roll.No</th>
                <th >Name</th>
                <th >Department</th>
                <th >Geder</th>
                <th >Age</th>
                
            </tr>
                            
             <tr>
                <td>{{ data.id }}</td>
                <td>{{ data.name }}</td>
                <td>{{ data.department }}</td>
                <td>{{ data.gender }}</td>
                <td>{{ data.age }}</td>
                

            </tr>

                
        </table> <br><br>

       

           <input type="submit" value="Yes, Delete" />
            <a href="/">Cancel </a>
            
   
</form>
</div>






{% endblock %}

templates/form.html
{% extends "base.html" %}

{% block content %}
<h1>
    Today we are going to discuss on FBV - Function based views.
</h1>
<div>
    <table style="width:100%"; border-spacing: 5px;>

             <tr>
                <th>Roll.no</th>
               <th>Name</th>
               <th >Age</th>
               <th >Gender</th>
               <th >Department</th>               
             </tr>
                     {% for a in stu %}
           <tr>
               <td>{{ a.id }} </td>
               <td>{{ a.name }}</td>
               <td>{{ a.age }}</td>
               <td>{{ a.gender }}</td>
               <td>{{ a.department }}</td>              

           </tr>
       {% endfor %}
   </table> 
<hr><hr>
<br><br>


For registration please fill in the form.

<div>
    <form action = "" method = "post">
        {% csrf_token %}
        {{form.as_p }}
        <input type="submit" value= "Submit">
    </form>
</div>




{% endblock %}

templates/get.html
<h1>Result is : {{ c }} </h1>

templates/home - Copy (4).html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>

        This is my Web page.
    </h1>
    
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}

This is my Home page.
{{stu}}<br>
    {% for i in names %}
    {{i}}
    {% endfor %}
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
    
<head>
  <title>Login</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


  <style>
    body,
    html {
      margin: 0;
      padding: 0;
      height: 100%;
      background: #7abecc !important;
    }
    .user_card {
      width: 350px;
      margin-top: auto;
      margin-bottom: auto;
      background: #74cfbf;
      position: relative;
      display: flex;
      justify-content: center;
      flex-direction: column;
      padding: 10px;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      border-radius: 5px;

    }

    .form_container {
      margin-top: 20px;
    }

    #form-title{
      color: #fff;
      
    }

    .login_btn {
      width: 100%;
      background: #33ccff !important;
      color: white !important;
    }
    .login_btn:focus {
      box-shadow: none !important;
      outline: 0px !important;
    }
    .login_container {
      padding: 0 2rem;
    }
    .input-group-text {
      background: #f7ba5b !important;
      color: white !important;
      border: 0 !important;
      border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
      box-shadow: none !important;
      outline: 0px !important;
    }

    #messages{
      background-color: grey;
      color: #fff;
      padding: 10px;
      margin-top: 10px;
    }
  </style>

</head>
<body>
  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">


          <h3 id="form-title">LOGIN</h3>
        </div>
        <div class="d-flex justify-content-center form_container">
          <form method="POST" action="login_reg">
            {% csrf_token %}
            <div class="input-group mb-3">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
              </div>
              <input type="text" name="username" placeholder="Username..." class="form-control">
            </div>
            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
              </div>
                <input type="password" name="password" placeholder="Password..." class="form-control" >
            </div>

              <div class="d-flex justify-content-center mt-3 login_container">
                <input class="btn login_btn" type="submit" value="Login">
                </div>
          </form>

        </div>
                {% for message in messages %}
                  {{ message }}
                {% endfor %}
        <div class="mt-4">
          <div class="d-flex justify-content-center links">
            Don't have an account? <a href="{% url 'EEE:register' %}" class="ml-2">Sign Up</a>
          </div>
      
        </div>
      </div>
    </div>
  </div>
</body>

</html>

templates/register.html
<!DOCTYPE html>
<html>
    
<head>
  <title>Login</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

  <style>
    body,
    html {
      margin: 0;
      padding: 0;
      height: 100%;
      background: #7abecc !important;
    }
    .user_card {
      width: 350px;
      margin-top: auto;
      margin-bottom: auto;
      background: #74cfbf;
      position: relative;
      display: flex;
      justify-content: center;
      flex-direction: column;
      padding: 10px;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      border-radius: 5px;

    }

    .form_container {
      margin-top: 20px;
    }

    #form-title{
      color: #fff;
    }
    .login_btn {
      width: 100%;
      background: #33ccff !important;
      color: white !important;
    }
    .login_btn:focus {
      box-shadow: none !important;
      outline: 0px !important;
    }
    .login_container {
      padding: 0 2rem;
    }
    .input-group-text {
      background: #f7ba5b !important;
      color: white !important;
      border: 0 !important;
      border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
      box-shadow: none !important;
      outline: 0px !important;
    }

  </style>

</head>
<body>
  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">
          <h3 id="form-title">REGISTER ACCOUNT</h3>
        </div>
        <div class="d-flex justify-content-center form_container">

          <form method="POST" action="">
            {% csrf_token %}
      
            <div class="input-group mb-3">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
              </div>
              {{ form.username }}
            </div>
            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
              </div>
              {{ form.email }}
              </div>
            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
              </div>
              {{ form.password1 }}
              </div>
            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
              </div>
              {{ form.password2 }}
              
              </div>

              <div class="d-flex justify-content-center mt-3 login_container">
              <input class="btn login_btn" type="submit" value="Register Account">
              </div>
          </form>
        </div>
    

    {{ form.errors }}
        <div class="mt-4">
          <div class="d-flex justify-content-center links">
            Already have an account? <a href="{% url 'EEE:login' %}" class="ml-2">Login</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
            /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
    //We start indexing at one because CSRF_token is considered and input field 
     */

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='Username..';
    form_fields[2].placeholder='Email..';
    form_fields[3].placeholder='Enter password...';
    form_fields[4].placeholder='Re-enter Password...';


    for (var field in form_fields){ 
      form_fields[field].className += ' form-control'
    }
  </script>
</body>
</html>

<!---

<h1>Register</h1>

<form method  = 'POST' action = 'register'>
  <h1>CreateUserForm</h1>
      {% csrf_token %}
      {{ form.username.label }}
      {{ form.username }}

{{ form.email.label }}
      {{ form.email }}
{{ form.password1.label }}
      {{ form.password1 }}
{{ form.password2.label }} ---------1
      {{ form.password2 }}

--->


<!---
          {%  for field in form %}
             {{ field.label }}  -----------2
             {{ field }}
             <br>
             
          {% endfor %}
--->

<!---
  <input type="submit" name="Create User">
  <br><hr>
</form>   ---------------1


--->

templates/rit.html
<h1>We are discussing about GET and POST requests.</h1>



GET request:
<form action = 'get1'>
    Enter the first number:<input type = 'text' name='num1'><br><br>
    Enter the second number:<input type = 'text' name='num2'><br><br>
    <input type = 'submit'>


</form>

POST request:

<form action = 'post1' method = 'post'>
    {% csrf_token %}
    Enter the first number:<input type = 'text' name='num1'><br><br>
    Enter the second number:<input type = 'text' name='num2'><br><br>
    <input type = 'submit'>


</form>

templates/student.html
{% extends "base.html" %}

{% block content %}

{%  for a in stu %}
{{a}}<br>
Roll.No : {{ a.id }}<br>
Name: {{a.name}}<br>
Age: {{a.age}}<br>
Department: {{a.contact}}<br>
Gender: {{a.gender}}<br><br>
<hr>
{% endfor %}


{% endblock %}

templates/update.html
{% extends "base.html" %}

{% block content %}


<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}

    <h4>    Do you want to Update this item ? </h4><br>
<div>
     <table style="width:100%"; border-spacing: 5px;>

        
              <tr>
                <th>Roll.No</th>
                <th >Name</th>
                <th >Department</th>
                <th >Phone number</th>
                <th >Address</th>
                
              </tr>
                    
            <tr>
                <td>{{ data.id }}</td>
                <td>{{ data.name }}</td>
                <td>{{ data.department }}</td>
                <td>{{ data.contact }}</td>
                <td>{{ data.address }}</td>
                

            </tr>
        
    </table> <br><br>
    <div>
		<h1>Enter the values to be updated here.</h1>
    			{{ form.as_p }}
    </div>

        <input type="submit" value="Yes, Update" />
        <a href="/">Cancel </a>
    </form>
</div>



{% endblock %}